namespace Enterprise.Documentation.Core.Application.DTOs.Approval;

/// <summary>
/// DTO for document edit decisions during approval workflow.
/// Used when reviewer makes decisions about suggested edits.
/// </summary>
public record CoreEditDecision
{
    /// <summary>
    /// Unique identifier for the edit suggestion
    /// </summary>
    public int EditId { get; init; }

    /// <summary>
    /// The section of the document being edited
    /// </summary>
    public string SectionName { get; init; } = string.Empty;

    /// <summary>
    /// Original content before edit
    /// </summary>
    public string OriginalContent { get; init; } = string.Empty;

    /// <summary>
    /// Suggested new content
    /// </summary>
    public string SuggestedContent { get; init; } = string.Empty;

    /// <summary>
    /// Decision: Accept, Reject, or Modify
    /// </summary>
    public EditDecisionType Decision { get; init; }

    /// <summary>
    /// If Decision is Modify, this contains the modified content
    /// </summary>
    public string? ModifiedContent { get; init; }

    /// <summary>
    /// Reviewer's comment on the decision
    /// </summary>
    public string? Comment { get; init; }

    /// <summary>
    /// Who made the decision
    /// </summary>
    public string ReviewedBy { get; init; } = string.Empty;

    /// <summary>
    /// When the decision was made
    /// </summary>
    public DateTime ReviewedDate { get; init; } = DateTime.UtcNow;

    /// <summary>
    /// Who edited the document
    /// </summary>
    public string EditedBy { get; init; } = string.Empty;

    /// <summary>
    /// Reason for the edit
    /// </summary>
    public string EditReason { get; init; } = string.Empty;
}

/// <summary>
/// DTO for updating document content during approval review.
/// Allows reviewers to make changes to the document before approval.
/// </summary>
public record CoreUpdateDocumentRequest
{
    /// <summary>
    /// ID of the document being updated
    /// </summary>
    public string DocumentId { get; init; } = string.Empty;

    /// <summary>
    /// ID of the approval request
    /// </summary>
    public int ApprovalId { get; init; }

    /// <summary>
    /// Section of document being updated
    /// </summary>
    public string SectionName { get; init; } = string.Empty;

    /// <summary>
    /// New content for the section
    /// </summary>
    public string UpdatedContent { get; init; } = string.Empty;

    /// <summary>
    /// Reason for the update
    /// </summary>
    public string UpdateReason { get; init; } = string.Empty;

    /// <summary>
    /// Who is making the update
    /// </summary>
    public string UpdatedBy { get; init; } = string.Empty;

    /// <summary>
    /// Whether to track this as a formal edit (for audit)
    /// </summary>
    public bool TrackAsEdit { get; init; } = true;

    /// <summary>
    /// Additional metadata about the update
    /// </summary>
    public Dictionary<string, string>? Metadata { get; init; }

    /// <summary>
    /// New document path after update
    /// </summary>
    public string? NewDocumentPath { get; init; }
}

/// <summary>
/// DTO for AI-generated or reviewer suggestions during approval.
/// Can be used for improvement recommendations, style changes, or corrections.
/// </summary>
public record CoreSuggestion
{
    /// <summary>
    /// Unique identifier for the suggestion
    /// </summary>
    public int SuggestionId { get; init; }

    /// <summary>
    /// Document this suggestion applies to
    /// </summary>
    public string DocumentId { get; init; } = string.Empty;

    /// <summary>
    /// Section of document the suggestion applies to
    /// </summary>
    public string SectionName { get; init; } = string.Empty;

    /// <summary>
    /// Type of suggestion
    /// </summary>
    public SuggestionType Type { get; init; }

    /// <summary>
    /// The actual suggestion text
    /// </summary>
    public string SuggestionText { get; init; } = string.Empty;

    /// <summary>
    /// Severity/priority of the suggestion
    /// </summary>
    public SuggestionSeverity Severity { get; init; }

    /// <summary>
    /// Original content being commented on
    /// </summary>
    public string? OriginalContent { get; init; }

    /// <summary>
    /// Suggested replacement content (if applicable)
    /// </summary>
    public string? SuggestedContent { get; init; }

    /// <summary>
    /// Who created the suggestion (AI, Reviewer, etc.)
    /// </summary>
    public string CreatedBy { get; init; } = string.Empty;

    /// <summary>
    /// Whether this was generated by AI
    /// </summary>
    public bool IsAIGenerated { get; init; }

    /// <summary>
    /// Confidence score for AI-generated suggestions (0-1)
    /// </summary>
    public decimal? ConfidenceScore { get; init; }

    /// <summary>
    /// When the suggestion was created
    /// </summary>
    public DateTime CreatedDate { get; init; } = DateTime.UtcNow;

    /// <summary>
    /// Status of the suggestion
    /// </summary>
    public SuggestionStatus Status { get; init; }

    /// <summary>
    /// Resolution notes (if accepted/rejected)
    /// </summary>
    public string? ResolutionNotes { get; init; }

    /// <summary>
    /// Who resolved the suggestion
    /// </summary>
    public string? ResolvedBy { get; init; }

    /// <summary>
    /// When the suggestion was resolved
    /// </summary>
    public DateTime? ResolvedDate { get; init; }

    /// <summary>
    /// Text content of the suggestion (alias for SuggestionText)
    /// </summary>
    public string Text => SuggestionText;

    /// <summary>
    /// Who suggested this (user or system) (alias for CreatedBy)
    /// </summary>
    public string SuggestedBy => CreatedBy;

    /// <summary>
    /// Category of the suggestion (derived from Type)
    /// </summary>
    public string Category => Type.ToString();
}

/// <summary>
/// Type of edit decision
/// </summary>
public enum EditDecisionType
{
    /// <summary>
    /// Accept the suggested edit as-is
    /// </summary>
    Accept,

    /// <summary>
    /// Reject the suggested edit
    /// </summary>
    Reject,

    /// <summary>
    /// Accept with modifications
    /// </summary>
    Modify
}

/// <summary>
/// Type of suggestion
/// </summary>
public enum SuggestionType
{
    /// <summary>
    /// Grammar or spelling correction
    /// </summary>
    GrammarCorrection,

    /// <summary>
    /// Style or formatting improvement
    /// </summary>
    StyleImprovement,

    /// <summary>
    /// Technical accuracy correction
    /// </summary>
    TechnicalCorrection,

    /// <summary>
    /// Clarification needed
    /// </summary>
    ClarificationNeeded,

    /// <summary>
    /// Additional information recommended
    /// </summary>
    AdditionalInfo,

    /// <summary>
    /// Consistency issue
    /// </summary>
    ConsistencyIssue,

    /// <summary>
    /// Best practice recommendation
    /// </summary>
    BestPractice,

    /// <summary>
    /// Other type of suggestion
    /// </summary>
    Other
}

/// <summary>
/// Severity level for suggestions
/// </summary>
public enum SuggestionSeverity
{
    /// <summary>
    /// Informational only
    /// </summary>
    Info,

    /// <summary>
    /// Low priority suggestion
    /// </summary>
    Low,

    /// <summary>
    /// Medium priority suggestion
    /// </summary>
    Medium,

    /// <summary>
    /// High priority - should be addressed
    /// </summary>
    High,

    /// <summary>
    /// Critical - must be addressed before approval
    /// </summary>
    Critical
}

/// <summary>
/// Status of a suggestion
/// </summary>
public enum SuggestionStatus
{
    /// <summary>
    /// Suggestion is pending review
    /// </summary>
    Pending,

    /// <summary>
    /// Suggestion has been accepted
    /// </summary>
    Accepted,

    /// <summary>
    /// Suggestion has been rejected
    /// </summary>
    Rejected,

    /// <summary>
    /// Suggestion implemented with modifications
    /// </summary>
    Modified,

    /// <summary>
    /// Suggestion deferred to future update
    /// </summary>
    Deferred
}